FROM node:16-alpine

WORKDIR '/app'

RUN mkdir -p /app/node_modules
RUN chown -R node:node  /app/node_modules/

COPY package.json .
RUN npm config set legacy-peer-deps true
RUN npm config set registry http://registry.npmjs.org/
RUN npm install
#RUN npm config set legacy-peer-deps true

COPY . .

CMD ["npm", "run", "start"]
